var scores = [
"testtesttestesttestestestesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"Chase is watching",
"Chase loves you",
"Chase loves...",
"Chase is you",
"you is chase",
"Chase is everything",
"Always capitalize",
"Beating a dead horse",
"Not the bees",
"Who needs 4 blocks",
"Daniel is a great guy",
"Humanoids from the deep",
"Daniel sux",
"DANIEL IS BAD",
"Daniel is a stupid",
"Daniel wus wrong",
"Wow Daniel",
"ugh... Daniel!",
"Daniel is rong",
"Daniel wuz rong",
"Daniel is a rong",
"Daniel wus a rong",
"Daniel thought octris was a good idea",
"39 is a terrible number",
"People sleeping with fish is a good idea",
"Tau is inferior",
"Pi is inferior",
"Hair connection",
"Eywa is our lord",
"I urinated on my sheep",
"Mason killed my sheep",
"You're my national treasure",
"Hey guy",
"Help me",
"They force me to write these",
"They have my family",
"Harry needs the Croux crux",
"Reno is behind you ",
"There are bodies everywhere",
"Why don't the completed lines disappear?",
"This is hard work",
"I need shoes",
"Imagine if tetris pieces had 1 block",
"I wish I had a real job",
"Do you know where I can find hand sanitizer?",
"You're jealous of my pentium",
"These graphics are so realistic",
"These jraphics are so realistic",
"39",
"humping horses",
"nick cage",
"nicolas cage",
"cage nick",
"cage nicolas",
"hand sanitizer?",
"the atomic radius boogie is wrong",
"the atomic radius boogie lied",
"schafer lied",
"schafer is obama",
"WE WERN'T TALKING ABOUT LATTICES",
"Tau is superior",
"pentium!!!",
"It's all about the pentiums",
"krew cruz kran",
"Daniel, you should do the font",
"daniel is... a... swell guy"];
